#!/bin/zsh

# PROFILE FILE, SET ENVIRONMENTAL VARIABLES HERE

# ~/ CLEAN UP
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/history"
